// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aatgvanjdalwaukpxgui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhdGd2YW5qZGFsd2F1a3B4Z3VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzE4NDIsImV4cCI6MjA2MTQwNzg0Mn0.1TqEWt57qpZd04RH2S_W9I2HTI9_3veMOjmsEsYlHqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);